services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# systemctl --user start docker-desktop
# docker compose build
# docker compose up -d

# forçar build sem cache
# docker compose build --no-cache

# se a docker engine não iniciar então executar os seguintes comandos e depois novamente os passos acima:

# systemctl --user stop docker-desktop
# rm -rf ~/.docker/desktop

